name: .NET Build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_NAME: ghcr.io/bursacmilan/ibricks-mqtt-broker:latest
      DOCKER_TARGET_PLATFORM: linux/arm64

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test

    - name: Dotnet publish
      run: dotnet publish ./ibricks-mqtt-broker-webapp/ibricks-mqtt-broker-webapp.csproj --configuration Release --output publishedOutput

    - name: Move docker file
      run: mv Dockerfile publishedOutput/Dockerfile

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: publishedOutput/
        platforms: linux/amd64,linux/arm64
        push: false
        tags:  ${{ env.DOCKER_TARGET_PLATFORM }}

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Push image
      run: docker push ${{ env.IMAGE_NAME }}